// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package usecase -source contract.go -destination contract_mock.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/gwassel/TasksOfWoe/internal/usecase/analytics/everyday_report/domain"
	gomock "go.uber.org/mock/gomock"
)

// Mockrepository is a mock of repository interface.
type Mockrepository struct {
	ctrl     *gomock.Controller
	recorder *MockrepositoryMockRecorder
	isgomock struct{}
}

// MockrepositoryMockRecorder is the mock recorder for Mockrepository.
type MockrepositoryMockRecorder struct {
	mock *Mockrepository
}

// NewMockrepository creates a new mock instance.
func NewMockrepository(ctrl *gomock.Controller) *Mockrepository {
	mock := &Mockrepository{ctrl: ctrl}
	mock.recorder = &MockrepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepository) EXPECT() *MockrepositoryMockRecorder {
	return m.recorder
}

// GetFieldForReport mocks base method.
func (m *Mockrepository) GetFieldForReport(ctx context.Context) (domain.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFieldForReport", ctx)
	ret0, _ := ret[0].(domain.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFieldForReport indicates an expected call of GetFieldForReport.
func (mr *MockrepositoryMockRecorder) GetFieldForReport(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFieldForReport", reflect.TypeOf((*Mockrepository)(nil).GetFieldForReport), ctx)
}
