name: Deploy to production

concurrency: production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted
    environment: production
    steps:
    - name: deploy
      run: |
        cd $PROJECT_PATH
        make down
        git switch main
        git pull
        make upd
